# global settings
title: "Surabaya-Ad"
description: "PT. Surabaya Mediatama - Media Campaign Specialist. Jasa periklanan Surabaya."
url: https://brehehe.github.io
mainurl: https://brehehe.github.io/sbyad
loading_teks: PT. Surabaya Mediatama
stylever: 2

plugins:
  - jekyll-avatar
  - jekyll-redirect-from
  - jekyll-seo-tag
