# global settings
# command 
# jekyll serve --incremental
# jekyll serve --incremental --host 0.0.0.0
title: "Surabaya-Ad"
description: "PT. Surabaya Mediatama - Media Campaign Specialist. Jasa periklanan Surabaya."
url: http://demo.surabaya-ad.com
#url: http://127.0.0.1:4000
mainurl: http://demo.surabaya-ad.com
#mainurl: http://127.0.0.1:4000
loading_teks: PT. Surabaya Mediatama
stylever: 9

info_logourl: logo-sbyad.png
info_logourlpp: pp-logo-sbyad.png
info_logourlppwht: img/logo/putih/logo-sby-ad-putih-500.png
#info_email: marketing.surabaya_ad@yahoo.com
info_email: info@surabaya-ad.com
info_whatsapp: 08123480099
info_nomor: 031-5611808
info_deskripsi: "<p>Surabaya Ad merupakan Perusahaan yang bergerak dibidang Advertising & Promotion dengan jangkauan bisnis 
di seluruh Indonesia, di bawah bendera PT. Surabaya Mediatama yang didirikan pada tanggal 12 Maret 2003 berdasarkan SK Menteri Kehakiman dan HAM R.I. 
Nomor : C-06883.HT.01.01.TH.2003. </p>
<p>Surabaya Ad telah 15 tahun berkegiatan bisnis dalam industri kreatif di Indonesia, 
baik Above The Line maupun Below The Line yang didukung oleh team berpengalaman dengan standart kerja terbaik dibidangnya.</p>"
info_alamat: "Kencanasari Timur XV/6 Surabaya 60224"
info_tel1: 031-5611808
info_tel2: 031-5619989

sosmed_facebook: https://www.facebook.com/surabayaad
sosmed_twitter: https://twitter.com/Surabaya_Ad
sosmed_instagram: https://www.instagram.com/surabayaad/

team_1:
  - dir-300px.jpg|Nono Suparno|Director
  - dodo-w-zaman.jpg|Dodo W. Zaman|Managing Director
  - white-300.jpg|Ria CH|Marketing Manager
team_2:
  - dwi-adi-c.jpg|Dwi Ady C.|Event Manager
  - anton-ar.jpg|Anton R.|Creative Director
  - white-300.jpg|Dony|Web programmer
team_3:
  - abdul-hamid.jpg|Abdul Hamid|Account Manager
  - dwi-andika.jpg|Dwi Andika|Finance Manager
  - tyas.jpg|Tyas Astuti|Media Planner
# for another paging on team4
team_4:
  - dir-300px.jpg|Nono Suparno|Director
  - dodo-w-zaman.jpg|Dodo W. Zaman|Managing Director
  - white-300.jpg|Ria CH|Marketing Manager
  - dwi-adi-c.jpg|Dwi Ady C.|Event Manager
team_5:
  - anton-ar.jpg|Anton R.|Creative Director
#  - white-300.jpg|Dony|Web programmer
  - abdul-hamid.jpg|Abdul Hamid|Account Manager
  - dwi-andika.jpg|Dwi Andika|Finance Manager
  - tyas.jpg|Tyas Astuti|Media Planner

client:
  - bpr-jatim.png|PT. BANK BPR JATIM
  - cimb-niaga.png|PT. BANK NIAGA
  - bank-bri.png|PT. BANK RAKYAT INDONESIA
  - panin-bank.png|PT. BANK PANIN
  - kanwil.png|KANWIL DJP JATIM I DAN II
  - rs-phc.png|RS PHC
  - heinz-abc.png|HEINZ ABC
  - nippon-paint.png|PT. NIPSEA PAINT AND CHEMICALS
  - profil-tank.png|PT. PROFILIA INDOTECH
  - arwinto-dtc.png|PT. ARWINTO INTAN WIJAYA

plugins:
  - jekyll-avatar
  - jekyll-redirect-from
  - jekyll-seo-tag
